### PR TITLE
IMPP: percent-encode handles in URI

### PR DESCRIPTION
**Pull request by rfc2822**
When users are allowed to enter IMPP schemes and handles, they (of course) enter invalid characters. I think the ez-vcard-calling application is responsible for filtering and purifying these values (handle=URI scheme and name=URI scheme specific part).

However, special characters are valid in the scheme specific part. Think of a messenger called "special", with handle "öffentlich" (German word) or a handle containing other special characters (Unicode smileys, etc).

Currently, ez-vcard uses `new URI(scheme, schemeSpecificPart, null)`, which is capable of handling special characters in `schemeSpecificPart`. However, then `ImppScribe` calls `toString()` which generates `special:öffentlich`. According to RFC 6350, a VCard URI is defined by RFC 3986, which defines an URI as (I only quote the relevant lines):

```
URI         = scheme ":" hier-part [ "?" query ] [ "#" fragment ]

      hier-part   = "//" authority path-abempty
                  / path-absolute
                  / path-rootless
                  / path-empty
      path          = path-abempty    ; begins with "/" or is empty
                    / path-absolute   ; begins with "/" but not "//"
                    / path-noscheme   ; begins with a non-colon segment
                    / path-rootless   ; begins with a segment
                    / path-empty      ; zero characters
      path-rootless = segment-nz *( "/" segment )
      segment       = *pchar
      segment-nz    = 1*pchar
      pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
```

So, unencoded values must not be in the URI (at least this is my interpretation).

Therefore I suggest to change `toString()` to `toASCIIString()´. In this case, special characters are encoded in UTF-8, which is basically ambiguous because nobody says that special characters have to be encoded as UTF-8. However, if unambiguity is required, the calling application could still filter special characters.

PS: This is a real world problem. Android lets users enter arbitrary IMPP handles and names, and DAVdroid tries to put them into a VCard (and vice versa). And you can't image the values users try to enter… (handle: "forum xxx user", name with special chars)

Please don't call me crazy. ;)

### CODE REVIEW

**Comment by rfc2822** [comment]
I forgot to test parsing (reading) the URIs again… maybe there would have to be updated something too?

**Comment by mangstadt** [comment]
Ack, I didn't see this until now!  I wish Github would send me email notifications!! I'll look it over.  Thank you for your input!

**Comment by mangstadt** [comment]
Hi rfc,

Thank you for pointing this out.  Yes, it makes sense to use `toASCIIString()` instead of `toString()` when outputting the URI to a vCard, since the specifications require special characters to be encoded.

In regards to parsing URIs, ez-vcard uses the `URI.create()` method.  This method does not take encoded characters into account.  I'm thinking of passing the string through the `URLDecoder.decode()` method before passing it to `URI.create()`.  Do you think this is a good approach?  Do you see any problems with it?  See the code below for a demonstration.

```java
String value = "special:%C3%B6ffentlich";
URI uri = URI.create(value);
System.out.println(uri.toString()); //outputs "special:%C3%B6ffentlich"
System.out.println(uri.toASCIIString()); //outputs "special:%C3%B6ffentlich"

String decodedValue = URLDecoder.decode(value, "UTF-8");
uri = URI.create(decodedValue);
System.out.println(uri.toString()); //outputs "special:öffentlich"
System.out.println(uri.toASCIIString()); //outputs "special:%C3%B6ffentlich"
```

**Comment by rfc2822** [comment]
The first version without `URLDecoder.decode` looks quite OK for me: there's no need convert an URI into a canonical version without encoded characters.

If there would be a need for decoding, I'd probably use `new URI`. Unfortunately, all that URI-handling is very error-sensitive and causes exceptions where you'd never expected them…

**Comment by mangstadt** [comment]
Thank you @rfc.

**Pull request merged**
