### PR TITLE
VCardRawWriter: make property name validation optional

### PR DESCRIPTION
**Pull request by blendmaster**
Last upstream parity patch.

For compatibility with certain non-conforming servers, namely icloud.

### CODE REVIEW

**Comment by mangstadt** [comment]
ez-vcard's validation framework is completely separate from its I/O functionality.  The presence of validation warnings will not prevent the vCard from being written.  vCards are only validated when you call the `VCard.validate()` method.

**Comment by blendmaster** [comment]
> ez-vcard's validation framework is completely separate from its I/O functionality. The presence of validation warnings will not prevent the vCard from being written.

That's not what I found here, this is in VCardRawWriter, and it throws real IAEs, not warnings. Icloud is in the wrong here for allowing non-spec properties, but without this workaround, you can't write back the same vcards that you can parse.

**Comment by mangstadt** [comment]
Oops sorry about that, misunderstood you.

My reasoning for this was that there are certain characters that are impossible to encode inside a property name without breaking the vCard syntax, such as colons, semicolons, and newlines.

For example, if you have a property named "FOO;BAR", iit would be written like so: 

`FOO;BAR:value`

But when this vCard is consumed, this line will be interpreted to mean: the property's name is "FOO", and it has one parameter named "BAR".

My reasoning was that it should treat this as a fatal error because it messes with the syntax (kind of like SQL injection).  The ez-vcard user may not be familiar with vCard syntax and think that naming a property "FOO;BAR" is totally fine.  But, if allowed, it would end up writing something you didn't intend.

But then again, maybe I'm being too strict.  Can you give me an example of a vCard where this issue comes into question?  I would really appreciate it.  Thanks for all your input.

**Comment by blendmaster** [comment]
The actual case I came across was:

    X-GOOGLE-OTHER_ORGANIZATIONS:Petco Cat Rescue--Fine Artist and Illustrator

I actually see now you committed https://github.com/mangstadt/ez-vcard/issues/35, which fixes this case more tightly. I'll use that instead.

**Comment by mangstadt** [comment]
Thank you for the example.  Yes, somebody contacted me about this issue a couple weeks ago, which was what caused me to open that issue you referenced.  The checking used to be much more strict, but I slimmed it down so it only checks for characters that break the syntax.  Thanks again.

**Pull request closed without merging**
