### PR TITLE
Update jackson dependency

### PR DESCRIPTION
**Pull request by thebino**
Updated library dependencies for jackson-core and jackson-databind

### CODE REVIEW

**Comment by mangstadt** [comment]
Why 2.8.11?  The latest version is 2.9.5 according to [Maven Central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.fasterxml.jackson.core%22%20AND%20a%3A%22jackson-core%22).

**Comment by thebino** [comment]
Needed by a conflict. Actually I haven't looked into maven, sorry for that.

**Comment by Chakosai** [comment]
New

**Comment by mangstadt** [comment]
Thanks @Chakosai.  I have since updated that dependency.  The latest version is 2.9.6.

**Pull request closed without merging**
