### PR TITLE
Jackson pretty printer

### PR DESCRIPTION
**Pull request by bgorven**
This is the pretty printer functionality we discussed.

Please take a look at the implementation, and let me know what you think.

### CODE REVIEW

**Comment by mangstadt** [comment]
Thank you, Buddy.

It's interesting how you are swapping out `Indenter` objects while writing the jCard.  Can you explain that?

I think I would like to merge the changes in your other pull request first, and then do the pretty printer stuff in a new pull request.  This pull request is named "Jackson pretty printer", yet it includes all the changes from your first pull request too.  I hope you are OK with that.

It would help so much if you disabled your code formatter before committing changes.  It's really hard to see the actual code changes you made, because so many of the changes are formatting-related.  Thank you.

**Comment by bgorven** [comment]
This works because I'm depending on an implementation (DefaultPrettyPrinter) rather than the interface. Thus it only works when the prettyPrinter field is not null, which it will only be if the JsonGenerator was created by the JCardRawWriter while `isIndent` was true. Indenters don't need to maintain internal state, as they get passed the number of levels to indent at the time they are called to write the indentation. This is by design, as each pretty printer will typically have different indenters for arrays and objects, so it makes sense to track the indentation level in the pretty printer. The `isInline` method is called by the pretty printer to determine whether to increase the indent; notice that I am returning false for this from the INLINE_INDENTER; partly because doing it the other way causes things to display weirdly, but also because I do want nested objects to be more indented than the arrays containing them, e.g:
```
    [ "email", {
        "pref" : "1"
      }, "text", "john.doe@company.com" ],
```
although, now that I think about it, it might be better just to set the object indenter to INLINE_INDENTER as well. That (with inline objects) is how jcard-example.json is formatted.

I'm sorry about all the noise in this pull request; I only noticed that after I created it—I should have branched off of your master, not mine. I've set that up on my local repo, but  I wasn't sure what to do with the branch I had already pushed. If you're suggesting that we close this and open a new PR with just the relevant changes, I agree. I'll push a new branch with just the relevant changes, applied to your current master, to my github repo and we can go from there.

**Comment by bgorven** [comment]
The new version is at https://github.com/bgorven/ez-vcard/commit/15813248e5b833cefdc6fb53892a529ccf42a938

I have also added a round-trip test, just by iterating over all the examples in the ezvcard/io/text/ folder, converting them to jcards, then converting the jcards back to vcard, so you can see how various jcards are formatted.

An issue with this test is that backslash-escaped commas in "unknown" properties are being deserialized as a literal backslash and comma, which is then being serialized as a backslash-escaped backslash and comma. This causes tests to fail when a jcard created from the original vcard is compared to a jcard created from the round-trip vcard:

[Original](https://github.com/bgorven/ez-vcard/blob/15813248e5b833cefdc6fb53892a529ccf42a938/src/test/resources/ezvcard/io/text/John_Doe_EVOLUTION.vcf#L15): X-EVOLUTION-FILE-AS:Doe\, John
[JCard](https://github.com/bgorven/ez-vcard/blob/15813248e5b833cefdc6fb53892a529ccf42a938/src/test/resources/ezvcard/io/json/roundtrip/John_Doe_EVOLUTION.json#L11): [ "x-evolution-file-as", { }, "unknown", "Doe\\, John" ],
[Converted from JCard](https://github.com/bgorven/ez-vcard/blob/15813248e5b833cefdc6fb53892a529ccf42a938/src/test/resources/ezvcard/io/json/roundtrip/John_Doe_EVOLUTION.vcf#L8): x-evolution-file-as:Doe\\\, John

**Comment by mangstadt** [comment]
Thank you Buddy.  The pretty printing looks so much better now.

Yes, I think we should close this pull request and create a new one.  Can you do that? If it's a problem, I can manually merge your changes from https://github.com/bgorven/ez-vcard/commit/15813248e5b833cefdc6fb53892a529ccf42a938.  I think the round-trip tests should be moved to another pull request as well.

The issue about backslash-escaped commas is happening because ez-vcard does not unescape escaped characters when parsing extended property values.  The [vCard 4.0 specs](http://tools.ietf.org/html/rfc6350#section-3.4) are pretty clear about requiring all property values to use backslash escaping, but the 3.0 and 2.1 specs are not as specific.  I wanted to preserve all the characters in extended property values incase an extended property has its own system for escaping characters.  Practically speaking though, I think backslash escaping is used pretty much by everyone.  So, I think I am going to change this due to the round-trip issue you brought up.

**Comment by bgorven** [comment]
Closing this PR. Refer to https://github.com/mangstadt/ez-vcard/pull/42 for the original PR, and https://github.com/mangstadt/ez-vcard/pull/48 for just the pretty printing changes.

**Pull request closed without merging**
